data_cfg:
  dataset_name: Frailty
  dataset_root: /your/path/to/sils
  frailty_label_file: opengait/frailty_label.csv
  dataset_partition: FrailtySet.json
  num_workers: 0
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: Frailty
  cache: true

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: false
  restore_hint: /your/path/to/DeepGaitV2-60000.pt
  save_name: Frailty
  sampler:
    batch_shuffle: false
    batch_size: 2
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 80 # limit the number of sampled frames to prevent out of memory
  eval_func: evaluate_scoliosis
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.5
    margin: 0.25
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 2.0
    scale: 20
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true
    class_weights: [1.130, 0.935, 0.935]

model_cfg:
  model: DeepGaitV2
  Backbone:
    mode: p3d
    in_channels: 1
    layers:
      - 1
      - 1
      - 1
      - 1
    channels: 
      - 64
      - 128 
      - 256
      - 512
    freeze_layers: false
    # From Part 1: Mean Acc 53.00%, Best Acc 66.67%, Best F1 60.32%
  SeparateBNNecks:
    class_num: 3
    parts_num: 16

optimizer_cfg:
  lr: 0.0001
  solver: AdamW
  weight_decay: 0.001

scheduler_cfg:
  gamma: 0.5
  milestones: # Learning Rate Reduction at each milestones
    - 15000
    - 30000
    - 50000
    - 70000
    - 90000
  scheduler: MultiStepLR

trainer_cfg:
  seed: 42  # Fixed seed for reproducibility
  enable_float16: false
  fix_BN: true
  log_iter: 100
  with_test: true
  optimizer_reset: True
  restore_ckpt_strict: false
  restore_hint: /your/path/to/DeepGaitV2-60000.pt
  save_iter: 500
  save_name: Frailty
  sync_BN: true
  T_max_iter: 10000
  total_iter: 10000
  find_unused_parameters: true
  grad_clip: 1.0
  sampler:
    batch_shuffle: false  
    batch_size:
      - 4
      - 4
    frames_num_fixed: 60
    frames_skip_num: 3
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: BaseSilCuttingTransform
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2
